import {
  clickButton, clickSubmitButton, clickTriedBeforeModalSwitch, clickTriedBeforeSearchButton, closeNotification, getCategoriesModalField, getCategorySearchField,
  getModalTitle, getNameModalField, getNameSearchField, getNotesModalField, getRatingModalField, getRatingSearchField, getReviewModalField, getSubmitButton,
  getTable, getTriedBeforeModalSwitch, getTriedBeforeSearchButton, selectRatingInModal, selectSearchCategory, selectSearchRating, typeInCategoriesModalField,
  typeInNameModalField, typeInNameSearchField, typeInNotesModalField, typeInReviewModalField, verifyNotesTooltip, verifyReviewTooltip, verifyRowNotesTooltip,
  verifyRowReviewTooltip, verifySearchFormEmpty, verifyTableHeaderCells, verifyTableRows,
} from './commands';

Cypress.Commands.addAll({
  getNameSearchField,
  getCategorySearchField,
  getRatingSearchField,
  getTriedBeforeSearchButton,
  getSubmitButton,
  getTable,
  typeInNameSearchField,
  selectSearchCategory,
  selectSearchRating,
  clickTriedBeforeSearchButton,
  clickSubmitButton,
  verifyTableHeaderCells,
  verifyTableRows,
  verifyReviewTooltip,
  verifyRowReviewTooltip,
  verifyNotesTooltip,
  verifyRowNotesTooltip,
  verifySearchFormEmpty,
  closeNotification,
  getModalTitle,
  getNameModalField,
  getCategoriesModalField,
  getTriedBeforeModalSwitch,
  getRatingModalField,
  getReviewModalField,
  getNotesModalField,
  typeInNameModalField,
  typeInCategoriesModalField,
  selectRatingInModal,
  typeInReviewModalField,
  typeInNotesModalField,
  clickTriedBeforeModalSwitch,
  clickButton,
});