/* tslint:disable */
/* eslint-disable */
/**
 * Personal restaurants knowledge base
 * This API allows to store and view personal ratings and notes  related to tried or ordered from restaurants  and places you may want to visit/order from in the future.  Note: all requests are performed in context of currently logged in user. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

