openapi: 3.0.0
info:
  title: Personal restaurants knowledge base
  description: |
    This API allows to store and view personal ratings and notes 
    related to tried or ordered from restaurants 
    and places you may want to visit/order from in the future.
    
    Note: all requests are performed in context of currently logged in user.
  version: '1'

paths:
  /restaurants:
    get:
      summary: Query restaurants by criteria
      operationId: queryRestaurantsByCriteria
      tags: [Restaurants]
      x-contracts:
        - contractId: 1
          name: Should return restaurants data
        - contractId: 2
          name: Should return bad request when no param is provided
      parameters:
        - name: nameBeginsWith
          in: query
          schema:
            type: string
          x-contracts:
            - contractId: 1
              value: KF
        - name: category
          in: query
          schema:
            $ref: '#/components/schemas/Category'
          x-contracts:
            - contractId: 1
              value: FAST_FOOD
        - name: triedBefore
          in: query
          schema:
            type: boolean
          x-contracts:
            - contractId: 1
              value: true
        - name: ratingAtLeast
          in: query
          schema:
            $ref: '#/components/schemas/Rating'
          x-contracts:
            - contractId: 1
              value: 3
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RestaurantData'
          x-contracts:
            - contractId: 1
              body:
                - name: KFC City Centre
                  categories: ['FAST_FOOD', 'CHICKEN']
                  triedBefore: true
                  rating: 4
                  review: 'Not my gig'
                - name: KFC Some Street
                  categories: ['FAST_FOOD', 'CHICKEN']
                  triedBefore: true
                  rating: 5
        400:
          description: When no param is provided
          x-contracts:
            - contractId: 2
    post:
      summary: Create a restaurant entry
      operationId: createRestaurant
      tags: [Restaurants]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestaurantData'
      responses:
        201:
          description: Restaurant created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                nullable: true
        409:
          description: Restaurant with given name already exists
  /restaurants/{restaurantName}:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
    get:
      summary: Get restaurant details
      operationId: getRestaurantDetails
      tags: [Restaurant entry]
      responses:
        200:
          $ref: '#/components/responses/RestaurantResponse'
        404:
          description: Restaurant with given name not found
    patch:
      summary: Rename the restaurant
      operationId: renameRestaurant
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        204:
          description: Restaurant renamed
        404:
          description: Restaurant with given name not found
    delete:
      summary: Delete the restaurant entry
      operationId: deleteRestaurant
      tags: [Restaurant entry]
      responses:
        204:
          description: Restaurant entry deleted
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/rating:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
    put:
      summary: Update rating of the restaurant
      description: Additionally marks the restaurant as tried
      operationId: updateRestaurantRating
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  $ref: '#/components/schemas/Rating'
              required:
                - rating
      responses:
        204:
          description: Rating updated
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/review:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
    put:
      summary: Update review of the restaurant
      description: Additionally marks the restaurant as tried
      operationId: updateRestaurantReview
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                review:
                  type: string
              required:
                - rating
      responses:
        204:
          description: Review updated
        404:
          description: Restaurant with given name not found
    delete:
      summary: Delete review of the restaurant
      operationId: deleteRestaurantReview
      tags: [Restaurant entry]
      responses:
        204:
          description: Review deleted
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/tried:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
    post:
      summary: Mark restaurant as tried
      operationId: markRestaurantAsTried
      tags: [Restaurant entry]
      responses:
        204:
          description: Marked as tried
        404:
          description: Restaurant with given name not found
    delete:
      summary: Mark restaurant as not tried
      operationId: markRestaurantAsNotTried
      description: Additionally removes the review and rating from the restaurant entry
      tags: [Restaurant entry]
      responses:
        204:
          description: Marked as not tried
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/categories:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
    post:
      summary: Add a category
      operationId: addRestaurantCategory
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: '#/components/schemas/Category'
              required:
                - name
      responses:
        200:
          description: Category added
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/Category'
        404:
          description: Restaurant with given name not found
    put:
      summary: Replace categories
      operationId: replaceRestaurantCategories
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              uniqueItems: true
              items:
                $ref: '#/components/schemas/Category'
      responses:
        204:
          description: Categories replaced
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/categories/{categoryName}:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
      - name: categoryName
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Category'
    delete:
      summary: Remove the category
      operationId: removeRestaurantCategory
      tags: [Restaurant entry]
      responses:
        204:
          description: Category removed
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/notes:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
    post:
      summary: Add a note
      operationId: addRestaurantNote
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
              required:
                - note
      responses:
        200:
          description: Note added
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  type: string
        404:
          description: Restaurant with given name not found
  /restaurants/{restaurantName}/notes/{noteIndex}:
    parameters:
      - $ref: '#/components/parameters/path.RestaurantName'
      - name: noteIndex
        in: path
        required: true
        schema:
          type: integer
    put:
      summary: Replace the note
      operationId: replaceRestaurantNote
      tags: [Restaurant entry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
              required:
                - note
      responses:
        204:
          description: Note replaced
        400:
          description: Note index is not a positive integer
        404:
          description: Restaurant with given name not found
    delete:
      summary: Remove the note
      operationId: removeRestaurantNote
      tags: [Restaurant entry]
      responses:
        204:
          description: Note removed
        400:
          description: Note index is not a positive integer
        404:
          description: Restaurant with given name not found

components:
  schemas:
    RestaurantData:
      type: object
      properties:
        name:
          type: string
        categories:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Category'
        triedBefore:
          type: boolean
        rating:
          $ref: '#/components/schemas/Rating'
        review:
          type: string
        notes:
          type: array
          items:
            type: string
    Category:
      type: string
      enum:
        - PIZZA
        - BURGER
        - SANDWICH
        - FAST_FOOD
        - PASTA
        - LUNCH
        - KEBAB
        - CHICKEN
        - VEGAN
        - RAMEN
        - SUSHI
        - ASIAN
        - INDIAN
        - OTHER
    Rating:
      type: integer
      minimum: 1
      maximum: 10
  parameters:
    path.RestaurantName:
      name: restaurantName
      in: path
      required: true
      schema:
        type: string
  responses:
    RestaurantResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RestaurantData'