name: E2E tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-e2e-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run frontend
        run: |
          cd frontend-app
          (npm install; npm start) &
          while ! nc -z localhost 3000; do sleep 1; done
      - name: Run backend
        run: |
          mvn install -DskipTests
          cd restaurants-knowledge-web
          mvn groovy:execute &
          until [ -f .dynamodb-port ]; do sleep 1; done
          mvn spring-boot:run -Dspring-boot.run.arguments="--amazon.aws.dynamodb-url=http://localhost:$(cat .dynamodb-port)" &
          while ! nc -z localhost 8080; do sleep 1; done
      - name: Execute E2E tests
        run: |
          cd frontend-app
          npm run e2e-test
      - name: Save screenshots artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend-app/cypress/screenshots
          retention-days: 1

