name: E2E tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-e2e-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run E2E tests
        run: |
          cd frontend-app
          npm install
          npm start &
          cd ..
          mvn groovy:execute &
          until [ -f .dynamodb-port ]; do sleep 1; done
          mvn spring-boot:run -Dspring-boot.run.arguments="--amazon.aws.dynamodb-url=http://localhost:$(cat .dynamodb-port)" &
          while ! nc -z localhost 8080; do sleep 1; done
          cd frontend-app
          npm run e2e-test
          
          
